package com.mobileclaw.app.runtime.memory

import com.mobileclaw.app.R
import com.mobileclaw.app.runtime.strings.AppStrings

object MemoryFixtures {
    fun seedItems(
        strings: AppStrings,
        nowEpochMillis: Long = System.currentTimeMillis(),
    ): List<MemoryItem> {
        return listOf(
            MemoryItem(
                memoryId = "mem-durable-style",
                logicalRecordId = "logical-durable-style",
                title = strings.get(R.string.memory_fixture_prefers_concise_title),
                contentText = strings.get(R.string.memory_fixture_prefers_concise_content),
                summaryText = strings.get(R.string.memory_fixture_prefers_concise_summary),
                lifecycle = MemoryLifecycle.DURABLE,
                scope = MemoryScope.GLOBAL,
                exposurePolicy = MemoryExposurePolicy.SHAREABLE_SUMMARY,
                syncPolicy = MemorySyncPolicy.SUMMARY_SYNC_READY,
                subjectKey = null,
                originApp = "agent_workspace",
                originDeviceId = "local_device",
                originUserId = "single_user",
                sourceType = MemorySourceType.USER_EDIT,
                confidence = 1.0,
                logicalVersion = 3,
                schemaVersion = 1,
                isPinned = true,
                isManuallyEdited = true,
                createdAtEpochMillis = nowEpochMillis,
                updatedAtEpochMillis = nowEpochMillis,
                expiresAtEpochMillis = null,
                evidenceRef = null,
            ),
            MemoryItem(
                memoryId = "mem-working-runtime",
                logicalRecordId = "logical-working-runtime",
                title = strings.get(R.string.memory_fixture_current_context_title),
                contentText = strings.get(R.string.memory_fixture_current_context_content),
                summaryText = strings.get(R.string.memory_fixture_current_context_summary),
                lifecycle = MemoryLifecycle.WORKING,
                scope = MemoryScope.APP_SCOPED,
                exposurePolicy = MemoryExposurePolicy.PRIVATE,
                syncPolicy = MemorySyncPolicy.LOCAL_ONLY,
                subjectKey = "workspace:primary_workspace",
                originApp = "agent_workspace",
                originDeviceId = "local_device",
                originUserId = "single_user",
                sourceType = MemorySourceType.RUNTIME_WRITEBACK,
                confidence = 0.92,
                logicalVersion = 1,
                schemaVersion = 1,
                isPinned = false,
                isManuallyEdited = false,
                createdAtEpochMillis = nowEpochMillis,
                updatedAtEpochMillis = nowEpochMillis,
                expiresAtEpochMillis = nowEpochMillis + 7 * 24 * 60 * 60 * 1000L,
                evidenceRef = "local://runtime/context",
            ),
            MemoryItem(
                memoryId = "mem-ephemeral-contact",
                logicalRecordId = "logical-ephemeral-contact",
                title = strings.get(R.string.memory_fixture_contact_pref_title),
                contentText = strings.get(R.string.memory_fixture_contact_pref_content),
                summaryText = strings.get(R.string.memory_fixture_contact_pref_summary),
                lifecycle = MemoryLifecycle.EPHEMERAL,
                scope = MemoryScope.CONTACT_SCOPED,
                exposurePolicy = MemoryExposurePolicy.SHAREABLE_SUMMARY,
                syncPolicy = MemorySyncPolicy.LOCAL_ONLY,
                subjectKey = "contact:alice",
                originApp = "messages",
                originDeviceId = "local_device",
                originUserId = "single_user",
                sourceType = MemorySourceType.INFERRED,
                confidence = 0.81,
                logicalVersion = 2,
                schemaVersion = 1,
                isPinned = false,
                isManuallyEdited = false,
                createdAtEpochMillis = nowEpochMillis,
                updatedAtEpochMillis = nowEpochMillis,
                expiresAtEpochMillis = nowEpochMillis + 3 * 24 * 60 * 60 * 1000L,
                evidenceRef = "local://messages/alice",
            ),
        )
    }
}
