package com.mobileclaw.app.ui.agentworkspace.model

import com.mobileclaw.app.runtime.session.RuntimeStatusSummary

data class RuntimeStatusUiModel(
    val headline: String = "",
    val stageLabel: String = "",
    val supportingText: String = "",
    val selectionModeLabel: String = "",
    val selectionReason: String = "",
    val selectionCandidateLines: List<String> = emptyList(),
    val selectionWarnings: List<String> = emptyList(),
    val toolId: String = "",
    val toolDisplayName: String = "",
    val toolSideEffectLabel: String = "",
    val toolScopeLines: List<String> = emptyList(),
    val toolVisibilityLabel: String = "",
    val toolVisibilityReason: String = "",
    val readScopeLabel: String = "",
    val readPreviewLines: List<String> = emptyList(),
    val readOutcomeLabel: String = "",
    val readOutcomeLines: List<String> = emptyList(),
    val sourceLabel: String = "",
    val trustStateLabel: String = "",
    val interopContractLabel: String = "",
    val uriGrantLabel: String = "",
    val routeSummary: String = "",
    val callerTrust: String = "",
    val structuredActionTitle: String = "",
    val structuredCompleteness: String = "",
    val structuredFieldLines: List<String> = emptyList(),
    val structuredWarnings: List<String> = emptyList(),
    val contributionSummaryLines: List<String> = emptyList(),
    val contributionDetailLines: List<String> = emptyList(),
    val knowledgeSupportLines: List<String> = emptyList(),
    val knowledgeCitationLines: List<String> = emptyList(),
    val knowledgeLimitationSummary: String = "",
    val extensionStatusLines: List<String> = emptyList(),
    val systemSourceStatusLines: List<String> = emptyList(),
    val systemSourceContributionLines: List<String> = emptyList(),
    val hasMissingSystemSourcePermissions: Boolean = false,
    val isBusy: Boolean = false,
    val awaitingInput: Boolean = false,
    val isTerminal: Boolean = false,
)

fun RuntimeStatusSummary.toUiModel(): RuntimeStatusUiModel = RuntimeStatusUiModel(
    headline = headline,
    stageLabel = stageLabel,
    supportingText = supportingText,
    isBusy = isBusy,
    awaitingInput = awaitingInput,
    isTerminal = isTerminal,
)
