package com.mobileclaw.app.runtime.extension

enum class RuntimeExtensionType {
    INGRESS,
    TOOL_PROVIDER,
    CONTEXT_SOURCE,
    EXPORT,
    IMPORT,
    SYNC_TRANSPORT,
}

enum class ExtensionPrivacyGuarantee {
    PRIVATE_BY_DEFAULT,
    SUMMARY_ONLY,
    EXPLICIT_POLICY_CHECK,
    TRUSTED_CONTEXT_ONLY,
}

enum class ExtensionTrustRequirement {
    NONE,
    TRUSTED_CALLER,
    PRIVILEGED_CONTEXT,
}

enum class ExtensionEnablementState {
    ACTIVE,
    DISABLED,
    DEGRADED,
    INCOMPATIBLE,
}

enum class RuntimeProviderSurface {
    GENERIC_TOOL,
    EXPLICIT_READ,
    EXPLICIT_MUTATION,
}

data class RuntimeExtensionRegistration(
    val extensionId: String,
    val extensionType: RuntimeExtensionType,
    val displayName: String,
    val contributedCapabilities: List<String>,
    val requiredRecordFields: List<String>,
    val requiredRuntimeMetadata: List<String>,
    val privacyGuarantee: ExtensionPrivacyGuarantee,
    val defaultEnablementState: ExtensionEnablementState,
    val trustRequirement: ExtensionTrustRequirement,
    val providerSurface: RuntimeProviderSurface = RuntimeProviderSurface.GENERIC_TOOL,
    val requiredPermissions: List<String> = emptyList(),
    val compatibilityVersionRange: IntRange = 1..1,
)

data class ExtensionCompatibilityReport(
    val extensionId: String,
    val displayName: String,
    val extensionType: RuntimeExtensionType,
    val isCompatible: Boolean,
    val reason: String,
    val missingFields: List<String> = emptyList(),
    val missingRuntimeMetadata: List<String> = emptyList(),
    val runtimeVersionSatisfied: Boolean = true,
)

data class ExtensionContributionSummary(
    val extensionId: String,
    val displayName: String,
    val extensionType: RuntimeExtensionType,
    val capabilitySummary: String,
    val privacySummary: String,
    val providerSurfaceSummary: String = "",
    val statusSummary: String,
    val enablementState: ExtensionEnablementState,
)

object DefaultRuntimeExtensionRegistrations {
    fun seeded(): List<RuntimeExtensionRegistration> = listOf(
        RuntimeExtensionRegistration(
            extensionId = "ingress.share.handoff",
            extensionType = RuntimeExtensionType.INGRESS,
            displayName = "Share Handoff Ingress",
            contributedCapabilities = listOf("external.share.handoff", "attachment.import"),
            requiredRecordFields = emptyList(),
            requiredRuntimeMetadata = listOf("interop.v1", "activity_share"),
            privacyGuarantee = ExtensionPrivacyGuarantee.PRIVATE_BY_DEFAULT,
            defaultEnablementState = ExtensionEnablementState.ACTIVE,
            trustRequirement = ExtensionTrustRequirement.NONE,
        ),
        RuntimeExtensionRegistration(
            extensionId = "provider.local.reply",
            extensionType = RuntimeExtensionType.TOOL_PROVIDER,
            displayName = "Local Reply Provider",
            contributedCapabilities = listOf("generate.reply"),
            requiredRecordFields = emptyList(),
            requiredRuntimeMetadata = listOf("tool_contract.v1", "provider.local"),
            privacyGuarantee = ExtensionPrivacyGuarantee.PRIVATE_BY_DEFAULT,
            defaultEnablementState = ExtensionEnablementState.ACTIVE,
            trustRequirement = ExtensionTrustRequirement.NONE,
        ),
        RuntimeExtensionRegistration(
            extensionId = "provider.calendar.read.local",
            extensionType = RuntimeExtensionType.TOOL_PROVIDER,
            displayName = "Calendar Read Provider",
            contributedCapabilities = listOf("calendar.read"),
            requiredRecordFields = emptyList(),
            requiredRuntimeMetadata = listOf("tool_contract.v1", "provider.read.local", "system_source.calendar"),
            privacyGuarantee = ExtensionPrivacyGuarantee.EXPLICIT_POLICY_CHECK,
            defaultEnablementState = ExtensionEnablementState.ACTIVE,
            trustRequirement = ExtensionTrustRequirement.NONE,
            providerSurface = RuntimeProviderSurface.EXPLICIT_READ,
            requiredPermissions = listOf("android.permission.READ_CALENDAR"),
        ),
        RuntimeExtensionRegistration(
            extensionId = "provider.contacts.read.local",
            extensionType = RuntimeExtensionType.TOOL_PROVIDER,
            displayName = "Contacts Read Provider",
            contributedCapabilities = listOf("contacts.read"),
            requiredRecordFields = emptyList(),
            requiredRuntimeMetadata = listOf("tool_contract.v1", "provider.read.local", "system_source.contacts"),
            privacyGuarantee = ExtensionPrivacyGuarantee.EXPLICIT_POLICY_CHECK,
            defaultEnablementState = ExtensionEnablementState.ACTIVE,
            trustRequirement = ExtensionTrustRequirement.NONE,
            providerSurface = RuntimeProviderSurface.EXPLICIT_READ,
            requiredPermissions = listOf("android.permission.READ_CONTACTS"),
        ),
        RuntimeExtensionRegistration(
            extensionId = "provider.calendar.write.local",
            extensionType = RuntimeExtensionType.TOOL_PROVIDER,
            displayName = "Calendar Write Provider",
            contributedCapabilities = listOf("calendar.write"),
            requiredRecordFields = emptyList(),
            requiredRuntimeMetadata = listOf("tool_contract.v1", "provider.mutation.local", "system_source.calendar"),
            privacyGuarantee = ExtensionPrivacyGuarantee.EXPLICIT_POLICY_CHECK,
            defaultEnablementState = ExtensionEnablementState.ACTIVE,
            trustRequirement = ExtensionTrustRequirement.NONE,
            providerSurface = RuntimeProviderSurface.EXPLICIT_MUTATION,
            requiredPermissions = listOf(
                "android.permission.READ_CALENDAR",
                "android.permission.WRITE_CALENDAR",
            ),
        ),
        RuntimeExtensionRegistration(
            extensionId = "provider.calendar.delete.local",
            extensionType = RuntimeExtensionType.TOOL_PROVIDER,
            displayName = "Calendar Delete Provider",
            contributedCapabilities = listOf("calendar.delete"),
            requiredRecordFields = emptyList(),
            requiredRuntimeMetadata = listOf("tool_contract.v1", "provider.mutation.local", "system_source.calendar"),
            privacyGuarantee = ExtensionPrivacyGuarantee.EXPLICIT_POLICY_CHECK,
            defaultEnablementState = ExtensionEnablementState.ACTIVE,
            trustRequirement = ExtensionTrustRequirement.NONE,
            providerSurface = RuntimeProviderSurface.EXPLICIT_MUTATION,
            requiredPermissions = listOf(
                "android.permission.READ_CALENDAR",
                "android.permission.WRITE_CALENDAR",
            ),
        ),
        RuntimeExtensionRegistration(
            extensionId = "context.contacts.system",
            extensionType = RuntimeExtensionType.CONTEXT_SOURCE,
            displayName = "Contacts Context Source",
            contributedCapabilities = listOf("contacts.read", "system_source.contacts"),
            requiredRecordFields = emptyList(),
            requiredRuntimeMetadata = listOf("system_source.contacts"),
            privacyGuarantee = ExtensionPrivacyGuarantee.TRUSTED_CONTEXT_ONLY,
            defaultEnablementState = ExtensionEnablementState.DEGRADED,
            trustRequirement = ExtensionTrustRequirement.PRIVILEGED_CONTEXT,
        ),
        RuntimeExtensionRegistration(
            extensionId = "context.calendar.system",
            extensionType = RuntimeExtensionType.CONTEXT_SOURCE,
            displayName = "Calendar Context Source",
            contributedCapabilities = listOf("calendar.read", "system_source.calendar"),
            requiredRecordFields = emptyList(),
            requiredRuntimeMetadata = listOf("system_source.calendar"),
            privacyGuarantee = ExtensionPrivacyGuarantee.TRUSTED_CONTEXT_ONLY,
            defaultEnablementState = ExtensionEnablementState.DEGRADED,
            trustRequirement = ExtensionTrustRequirement.PRIVILEGED_CONTEXT,
        ),
        RuntimeExtensionRegistration(
            extensionId = "export.summary.bundle",
            extensionType = RuntimeExtensionType.EXPORT,
            displayName = "Summary Bundle Export",
            contributedCapabilities = listOf("export.summary"),
            requiredRecordFields = listOf(
                "logicalRecordId",
                "summaryText",
                "exposurePolicy",
                "syncPolicy",
                "schemaVersion",
            ),
            requiredRuntimeMetadata = listOf("portability.v1"),
            privacyGuarantee = ExtensionPrivacyGuarantee.SUMMARY_ONLY,
            defaultEnablementState = ExtensionEnablementState.ACTIVE,
            trustRequirement = ExtensionTrustRequirement.NONE,
        ),
        RuntimeExtensionRegistration(
            extensionId = "import.portability.bundle",
            extensionType = RuntimeExtensionType.IMPORT,
            displayName = "Portability Bundle Import",
            contributedCapabilities = listOf("import.summary", "import.full"),
            requiredRecordFields = listOf("logicalRecordId", "schemaVersion"),
            requiredRuntimeMetadata = listOf("portability.v1"),
            privacyGuarantee = ExtensionPrivacyGuarantee.EXPLICIT_POLICY_CHECK,
            defaultEnablementState = ExtensionEnablementState.DISABLED,
            trustRequirement = ExtensionTrustRequirement.TRUSTED_CALLER,
        ),
        RuntimeExtensionRegistration(
            extensionId = "sync.transport.summary",
            extensionType = RuntimeExtensionType.SYNC_TRANSPORT,
            displayName = "Summary Sync Transport",
            contributedCapabilities = listOf("sync.summary"),
            requiredRecordFields = listOf(
                "logicalRecordId",
                "logicalVersion",
                "originDeviceId",
                "originUserId",
                "syncPolicy",
                "schemaVersion",
            ),
            requiredRuntimeMetadata = listOf("sync_transport.v1"),
            privacyGuarantee = ExtensionPrivacyGuarantee.SUMMARY_ONLY,
            defaultEnablementState = ExtensionEnablementState.DISABLED,
            trustRequirement = ExtensionTrustRequirement.TRUSTED_CALLER,
        ),
        RuntimeExtensionRegistration(
            extensionId = "provider.portability.full",
            extensionType = RuntimeExtensionType.TOOL_PROVIDER,
            displayName = "Full Portability Provider",
            contributedCapabilities = listOf("export.full", "preview.portability"),
            requiredRecordFields = listOf(
                "logicalRecordId",
                "contentText",
                "summaryText",
                "exposurePolicy",
                "syncPolicy",
                "schemaVersion",
            ),
            requiredRuntimeMetadata = listOf("tool_contract.v1", "portability.v1"),
            privacyGuarantee = ExtensionPrivacyGuarantee.EXPLICIT_POLICY_CHECK,
            defaultEnablementState = ExtensionEnablementState.DISABLED,
            trustRequirement = ExtensionTrustRequirement.NONE,
        ),
    )
}
